name: LifeLine_Strategy
on:
  schedule:
    - cron: '36 7 * * 1-5' # 北京时间 15:30 (UTC 7:30)
  workflow_dispatch:      # 支持手动运行
  push:
    paths:
      - 'LifeLine_Strategy.py'
      - '.github/workflows/LifeLine_Strategy.yml'

jobs:
  filter_stocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas numpy

      - name: Run LifeLine Strategy
        run: python LifeLine_Strategy.py

      - name: Commit and Push Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto Update: LifeLine Scan $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
